server:
  port: 18081

spring:
  application:
    name: Alibaba-MCP-Server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/ai?useSSL=false&serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
    mcp:
      server:
        name: spring-ai-mcp-server
        protocol: STREAMABLE # SSE、STREAMABLE、STATELESS
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false
logging:
  level:
    org.springframework.ai: DEBUG
