server:
  port: 18082
spring:
  application:
    name: AgentCustomerServer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/agent?serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      max-active: 10
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
    mcp:
      server:
        name: agent-customer-mcp-server
        protocol: STREAMABLE # SSE、STREAMABLE、STATELESS
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        instructions: "This reactive server provides time information tools and resources"
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate # validate、update、create、create-drop
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
logging:
  level:
    org.springframework.ai: DEBUG