server:
  port: 18081

spring:
  application:
    name: Alibaba-FunctionCalling
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/ai?useSSL=false&serverTimezone=UTC
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        protocol: streamable # SSE、STREAMABLE、STATELESS
        type: ASYNC  # Recommended for reactive applications
        instructions: "This server provides function calling capabilities for various tools and resources"
        request-timeout: 60s
        streamable-http:
          keep-alive-interval: 30s
          mcp-endpoint: /mcp
          disallow-delete: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
logging:
  level:
    org.springframework.ai: DEBUG